// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Message string `json:"message"`
	User    *User  `json:"user"`
}

type DeleteUserResponse struct {
	Message string `json:"message"`
}

type EditUserResponse struct {
	Message string `json:"message"`
	User    *User  `json:"user"`
}

type EditedUser struct {
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Avatar    string `json:"avatar"`
	Birthday  int    `json:"birthday"`
	Bio       string `json:"bio"`
	Facebook  string `json:"facebook"`
	Instagram string `json:"instagram"`
	Twitter   string `json:"twitter"`
}

type Token struct {
	Token    string `json:"token"`
	ExpireAt int    `json:"expireAt"`
}

type User struct {
	ID        int    `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Avatar    string `json:"avatar"`
	Birthday  int    `json:"birthday"`
	Bio       string `json:"bio"`
	Facebook  string `json:"facebook"`
	Instagram string `json:"instagram"`
	Twitter   string `json:"twitter"`
	IsAdmin   bool   `json:"isAdmin"`
	CreatedAt int    `json:"createdAt"`
	UpdatedAt int    `json:"updatedAt"`
}

type GetAllUsersResponse struct {
	Message string  `json:"message"`
	Users   []*User `json:"users"`
}

type GetUserByIDResponse struct {
	Message string `json:"message"`
	User    *User  `json:"user"`
}
